name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Builds C# codebase
      run: dotnet build
    - name: Run C# tests
      run: dotnet test
    - name: Run NPM install
      working-directory: ./DotnetTemplate.Web
      run: npm install
    - name: Build NPM code
      working-directory: ./DotnetTemplate.Web
      run: npm run build
    - name: Run TS linter
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
    - name: Run TS tests
      working-directory: ./DotnetTemplate.Web
      run: npm t
    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
      if: always()
  dockerhub:
    needs: build
    name: Auto publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: print the docker hub username
      run: echo ${{ secrets.DOCKER_HUB_USERNAME }}
    - name: login into docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: build docker image
      run: docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/dotnetteplate:${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: publish to docker hub
      run: docker publish ${{ secrets.DOCKER_HUB_USERNAME }}/dotnettemplate:${{ github.ref }}